name: ${COMPOSE_PROJECT_NAME:-viscocity-landing}

services:
  app:
    container_name: ${CONTAINER_NAME:-viscocity-landing}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE_NAME:-viscocity-landing}:latest
    env_file:
      - ../.env.production
    ports:
      - '${PORT:-3001}:80'
    networks:
      - pos-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  pos-network:
    external: true
