name: ${COMPOSE_PROJECT_NAME:-viscocity-landing}

services:
  app:
    container_name: ${CONTAINER_NAME:-viscocity-landing}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE_NAME:-viscocity-landing}:latest
    ports:
      - '${PORT:-3001}:80'
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
